### ISSUE TITLE
Version Deprecation

### ISSUE THREAD

**Issue by skategui** [parse-community/ParseFacebookUtils-Android#32]
Hey guys,

I received this notification from FB. I noticed this lib is using the version 4.24 of the FB SDK. Maybe it worths updating it soon ? 

`Your App, is currently accessing Graph API v2.5 which will reach the end of its 2-year lifetime on 12 April, 2018. To ensure a smooth transition, please migrate all calls to Graph API v2.6 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.
`

Thanks

**Comment by FridaySG** [comment]
Yeah, anybody know if this library (as well as the iOS version) will continue to work after April 12?

**Comment by rogerhu** [comment]
We should fix and update...care to take a stab? :)

**Comment by FridaySG** [comment]
@rogerhu I'll be honest I'm not sure if I have the necessary skill-set to do so but I'm definitely not opposed to trying. I'll see what I can do :). In the meantime, do you know if the changes Facebook is making April 12 will break Facebook login for the apps currently using this lib?

**Comment by rogerhu** [comment]
That's a good question to investigate...most of the changes are likely related to permissions so the login experience can't be asking for ones that are not explicitly allowed.

**Comment by Jawnnypoo** [comment]
This lib uses the most up to date version of the Facebook SDK, we are good to go here!
