### ISSUE TITLE
Release 1.10.6 on bintray doesn't have a particular commit

### ISSUE THREAD

**Issue by r21nomi** [parse-community/ParseFacebookUtils-Android#40]
Thank you for your new release v4-1.10.6.
But I found your [new release on bintray](https://bintray.com/parse/maven/ParseFacebookUtils-Android/1.10.6) doesn't include [this commit](https://github.com/parse-community/ParseFacebookUtils-Android/commit/b393d81a003aab37253e2138c3e7067a05494abe) in spite of your tag v4-1.10.6.on github have it.

I mean, there is a differences between bintray and github tag.

FYI, I checked the class in aar file by downloading from bintray.

Please confirm it.

Thanks.

**Comment by rogerhu** [comment]
Thanks..re released...
