### ISSUE TITLE
Failed to resolve: com.github.parse-community:ParseFacebookUtils-Android:1.18.4

### ISSUE THREAD

**Issue by kishangohel** [parse-community/ParseFacebookUtils-Android#44]
App Gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.win.gpsproject"
        minSdkVersion 17
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

ext{
    supportLibVer = '27.1.1'

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "com.android.support:appcompat-v7:$supportLibVer"
    implementation "com.android.support:cardview-v7:$supportLibVer"
    implementation "com.android.support:design:$supportLibVer"
    implementation "com.android.support:support-v4:$supportLibVer"
    implementation "com.android.support:support-annotations:$supportLibVer"
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    //dagger 2
    implementation 'com.google.dagger:dagger:2.17'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.17'
    implementation 'com.google.dagger:dagger-android-support:2.17'
    // if you use the support libraries
    //parse
    implementation 'com.github.parse-community.Parse-SDK-Android:parse:1.18.4'
    implementation 'com.github.parse-community:ParseFacebookUtils-Android:1.18.4'
  /*  implementation 'com.github.parse-community:ParseFacebookUtils-Android:1.18.4'
    implementation 'com.github.parse-community:ParseTwitterUtils-Android:1.18.4'*/
    // Butter Knife
    implementation 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
}

Project Gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by daydreamer1222** [comment]
I'm having the same issue. Do you happen to solve this??

**Comment by Jawnnypoo** [comment]
Latest version is 1.12.0, which is found in the README.
